### ISSUE TITLE
Version 1.2.2 (in fact any release after 1.1.11) fails to load - UnitOfApparentPower.KILO_VOLT_AMPERE AttributeError

### ISSUE THREAD

**Issue by Russell-williams61** [TypQxQ/Sigenergy-Home-Assistant-Integration#110]
**Version**: 1.2.2 (also affects versions after 1.1.11)

**Home Assistant Version**: [Your HA version - check Settings → About]

**Problem**: Integration fails to load after updating from v1.1.11 to v1.2.2

**Error**:
AttributeError: type object 'UnitOfApparentPower' has no attribute 'KILO_VOLT_AMPERE'. 
Did you mean: 'VOLT_AMPERE'?

**Location**: /config/custom_components/sigen/static_sensor.py, line 89

**Root Cause**: Home Assistant Core no longer supports UnitOfApparentPower.KILO_VOLT_AMPERE 
constant. Only VOLT_AMPERE is available.

**Workaround**: Reverted to v1.1.11 successfully

**Full Error Log**:
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 5:52:38 PM (3 occurrences)
Last logged: 5:53:42 PM
Error setting up entry Sigen Plant for sigen
Error setting up entry Sigen Plant 2 for sigen
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1260, in _load_platform
cache[full_name] = self._import_platform(platform_name)
~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1292, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
return func(*args, **kwargs)
File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/sigen/sensor.py", line 38, in <module>
from .static_sensor import StaticSensors as SS
File "/config/custom_components/sigen/static_sensor.py", line 24, in <module>
class StaticSensors:
...<1817 lines>...
]
File "/config/custom_components/sigen/static_sensor.py", line 89, in StaticSensors
native_unit_of_measurement=UnitOfApparentPower.KILO_VOLT_AMPERE,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfApparentPower' has no attribute 'KILO_VOLT_AMPERE'. Did you mean: 'VOLT_AMPERE'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/sigen/__init__.py", line 78, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2569, in async_forward_entry_setups
await integration.async_get_platforms(platforms)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
import_future.result()
~~~~~~~~~~~~~~~~~~~~^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
import_future.result()
~~~~~~~~~~~~~~~~~~~~^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
import_future.result()
~~~~~~~~~~~~~~~~~~~~^^
[Previous line repeated 2 more times]
File "/usr/src/homeassistant/homeassistant/loader.py", line 1161, in async_get_platforms
platforms.update(self._load_platforms(platform_names))
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _load_platforms
platform_name: self._load_platform(platform_name)
~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1280, in _load_platform
raise ImportError(
f"Exception importing {self.pkg_path}.{platform_name}"
) from err
ImportError: Exception importing custom_components.sigen.sensor
